### ISSUE TITLE
Plugin (Directory)

### ISSUE THREAD

**Issue by Hasan-Shaker** [xperseguers/staffdirectory#4]
- [x] - Ajouter la possibilité de mettre un point d’entrée
- [x] - Si aucune organisation n’est sélectionnée, lister toutes les personnes
- [ ] - Ajouter un bouton « lister les personnes des sous-organisations  de l’organisation sélectionnée »

**Comment by xperseguers** [comment]
- English please!
- That's a lot of different stuff to do, this should better be (partially) distinct tickets
- Ticket's description shall better describe the context of what is asked, this is way too vague

=> I'll see what I can do anyway :)

**Comment by xperseguers** [comment]
Last point is done already, that's the whole purpose of mode `DIRECTORY`, it will list all persons of an organization, and thus from any suborganization as well, as they belong to the selected organization(s).

**Comment by xperseguers** [comment]
Closing this ticket in its current state, don't see the point of the last task without further information and rationale. And as with all my extensions, I expect a single feature request per ticket, not a whole bunch of stuff to do, and clearly explained on what and why. Thx.
